site_name: Proyecto de Marco Álvarez Guardiola
site_url: https://1911234Marco.github.io/proyecto-mkdocs/
theme:
    name: material

nav:
    - Inicio: index.md
    - Sobre mí: sobremi.md
    - Proyectos: proyectos.md
    - Contacto: contacto.md